### ISSUE TITLE
how to deal with opencv2/core/core.hpp when i use kinetic?

### ISSUE THREAD

**Issue by zhang261007** [ANYbotics/grid_map#165]
In file included from /opt/ros/kinetic/include/grid_map_ros/GridMapRosConverter.hpp:28:0,
                 from /home/zmramost/build_mode/src/build_baselink/src/point_process.cpp:26:
/opt/ros/kinetic/include/cv_bridge/cv_bridge.h:43:33: fatal error: opencv2/core/core.hpp: No such file or directory
compilation terminated.

**Comment by zhang261007** [comment]
while i try find_package(cv_bridge) then it runs well

**Comment by maximilianwulf** [comment]
It is added as a dependency now.

**Comment by sasilva1998** [comment]
Hi, I installed `grid_map` using apt but I am getting the same issue regarding `opencv`. I am using noetic and ubuntu 20. How could I fix it?
