### ISSUE TITLE
Meta-package missing some sub-packages

### ISSUE THREAD

**Issue by lorenwel** [ANYbotics/grid_map#182]
E.g. grid_map_octomap or grid_map_costmap_2d.
Is this intentional?

**Comment by pfankhauser** [comment]
Nope, that's not intentional. I will fix it or you can create a PR if urgent, ok?

**Comment by lorenwel** [comment]
Ok, thanks. 
It's not urgent. Simply requires one to build those packages separately if they're needed. All else is working.
