### ISSUE TITLE
addLayerFromImage height scaling and map duplicate

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [ANYbotics/grid_map#192]
Hi @pierrefranklin ,
My goal is converting image to grid map . For this purpose I used `addLayerFromImage` as follows:
```

cv::Mat image= cv::imread(file, CV_LOAD_IMAGE_COLOR);
    bool res=  grid_map::GridMapCvConverter::addLayerFromImage<unsigned short, 3>(image,"elevation",gridMap);
```

Although, my map shows duplicate and having height scaling. 
![heightmapscaled](https://user-images.githubusercontent.com/3111976/49163365-d142fa80-f324-11e8-9734-25934d9c9eea.png)

Is it a problem with height scaling conversion?
Regards,
Bruno

**Comment by joshjowen** [comment]
It appears to me that you're file is saved as 16-bit but you are loading it with cv::imread as 8-bit. try changing
` cv::imread(file, CV_LOAD_IMAGE_COLOR);` 
to 
`cv::imread(file, CV_LOAD_IMAGE_COLOR | CV_LOAD_IMAGE_ANYDEPTH);`

**Comment by BrunoEduardoCSantos** [comment]
It worked out @joshjowen ! Thanks a lot!
