### ISSUE TITLE
Algorithm for SDF generation

### ISSUE THREAD

**Issue by raghul9706** [ANYbotics/grid_map#201]
Hi, 
               Thanks for providing such an excellent package. I am trying to use the grid map to sdf conversion. Can you please specify the algorithm behind sdf construction, so that I could get clearer on how it's being done?

**Comment by pfankhauser** [comment]
Hi @raghul9706,
Grid Map SDF is based on this work ([PDF](http://cs.brown.edu/people/pfelzens/papers/dt-final.pdf)):

    Distance Transforms of Sampled Functions
    P. Felzenszwalb, D. Huttenlocher
    Theory of Computing, Vol. 8, No. 19, September 2012

-Péter

**Comment by raghul9706** [comment]
Hi @pfankhauser 
       Thank you so much.
