### ISSUE TITLE
Image size does not correspond to grid map size

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [ANYbotics/grid_map#208]
Hi ,
My goal loading an image to an elevation grid map. For this purpose I use the following code:

```
   cv::Mat image= cv::imread(file, CV_LOAD_IMAGE_COLOR | CV_LOAD_IMAGE_ANYDEPTH);
    bool res=  grid_map::GridMapCvConverter::addLayerFromImage<unsigned short, 4>(image, "elevation",gridMap);
```
I obtained the following error:

> Image size does not correspond to grid map size

![map](https://user-images.githubusercontent.com/3111976/55812975-db031880-5ae3-11e9-9c6e-d8d2892d8bc9.png)

Any ideas what could be happening?
Thanks in advance,
Bruno

**Comment by hardesh** [comment]
Hi @brunoeducsantos!
How did you solve this error?

**Comment by brunoeducsantos** [comment]
Hi @hardesh , 
With the current version this issue is solved I  guess.

**Comment by hardesh** [comment]
Hi @brunoeducsantos,
Unfortunately I encountered this issue. I'm trying to find a work around

**Comment by maximilianwulf** [comment]
Hey @hardesh, can you submit your issue as a unit test?

**Comment by hardesh** [comment]
@maximilianwulf Sure! I'll try to submit a PR on this weekend. For now, I've found a workaround

**Comment by hardesh** [comment]
Hi @maximilianwulf,
I had tried something similar as done in [this](https://github.com/ANYbotics/grid_map/blob/539f9db782e73cd48a112a6a72f3dbc11868d80f/grid_map_cv/test/GridMapCvTest.cpp#L118) test case. Not sure if it's passing currently.

**Comment by maximilianwulf** [comment]
Did you manage to submit the test?

**Comment by hardesh** [comment]
I had tried out some functons which are already there in [this](https://github.com/ANYbotics/grid_map/blob/539f9db782e73cd48a112a6a72f3dbc11868d80f/grid_map_cv/test/GridMapCvTest.cpp#L118) test. It's already there. So, I didn't submit the test
