### ISSUE TITLE
Crash when changing topic before first message

### ISSUE THREAD

**Issue by StefanFabian** [ANYbotics/grid_map#210]
Steps to reproduce:

1. Add display
2. Select a topic that doesn't publish any messages
3. Switch to a different topic

Reason: The destructor of GridMapVisual does not check whether the manual object was created before destroying it. If computeVisualization wasn't called, the manual object is not initialized.

I've made a pull request with a fix.

**Comment by maximilianwulf** [comment]
Hi @StefanFabian, 

thank you very much for the pull request. We will check it.
