### ISSUE TITLE
Polygon Iterator issue. Is the frame relevant?

### ISSUE THREAD

**Issue by sasupe** [ANYbotics/grid_map#226]
Hi @maximilianwulf and team!
This library has been a great help to manipulate 2.5D data! Thanks!

I am using polygon iterator as shown in the gif to iterate through all the points inside it. While making grid_map::Polygon polygon it is attached to a sensor frame on the robot and the points are defined with respect to that. The map is attached to a fixed frame but moves according robot's position.

In the gif, I am just printing the loop count in the iterator loop. It seems to have a constant value at beginning but then becomes zero. 

Should grid_map::Polygon points be defined only in the map frame? That is  grid_map::Polygon is not actually moving with the robot and the points are being defined in the fixed map frame? Or what else could be the issue?

Thanks.

![polygon_error](https://user-images.githubusercontent.com/43161849/76473941-68c04580-63d0-11ea-8b91-12a1a69e7669.gif)

**Comment by maximilianwulf** [comment]
Hey @sasupe, happy to hear to you like it.

Can you share a code snippet? How do you define the polygon?
I think it depends on that.
