### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by jspricke** [ANYbotics/grid_map#230]
please provide a noetic release.

**Comment by jspricke** [comment]
I've opened a PR with fixes for this in #231.

**Comment by wxmerkt** [comment]
Friendly ping - would it be possible to release this package into the ROS buildfarm for Noetic? Thanks!

**Comment by maximilianwulf** [comment]
Yes, we are working on it. I guess it will be released soon. Thank you for your patience.

**Comment by maximilianwulf** [comment]
Short update on it, we should soon have the Noetic release. Thank you for your patience.

**Comment by julianraheema** [comment]
Please we need noetic release.

**Comment by maximilianwulf** [comment]
Hey all, all release jobs of grid map have passed. I am currently checking the devel jobs. But I guess the debians are ready to go. 
![Screenshot from 2021-01-21 09-58-43](https://user-images.githubusercontent.com/5656831/105327654-71c49a80-5bcf-11eb-8489-2aa26fd997a0.png)

Let me know if you have issues and thank you for your patience.
