### ISSUE TITLE
Error grid_map_pcl

### ISSUE THREAD

**Issue by brunoeducsantos** [ANYbotics/grid_map#247]
Hi,
Thanks for your awesome package.
While trying to compiling the package, I had the following error:

``` 
/home/bruno/grid_ws/devel/lib/libgrid_map_pcl.so: undefined reference to `typeinfo for YAML::BadConversion'
/home/bruno/grid_ws/devel/lib/libgrid_map_pcl.so: undefined reference to `YAML::BadConversion::~BadConversion()'
/home/bruno/grid_ws/devel/lib/libgrid_map_pcl.so: undefined reference to `vtable for YAML::BadConversion'
/home/bruno/grid_ws/devel/lib/libgrid_map_pcl.so: undefined reference to `pcl::search::Search<pcl::PointXYZ>::getName[abi:cxx11]() const'

``` 

Any help would be appreciated.

Regards,
Bruno

**Comment by maximilianwulf** [comment]
Hey @brunoeducsantos, which branch are you using?

**Comment by brunoeducsantos** [comment]
Master

**Comment by brunoeducsantos** [comment]
I tried this on `GridMapPclLoader` ,
```
#include <pcl/search/impl/search.hpp>
#ifndef PCL_NO_PRECOMPILE
#include <pcl/impl/instantiate.hpp>
#include <pcl/point_types.h>
PCL_INSTANTIATE(Search, PCL_POINT_TYPES)
```
And it sorted the pcl issue

**Comment by maximilianwulf** [comment]
Hm interesting, so it is solved?

**Comment by brunoeducsantos** [comment]
The Yaml issue hasn't been solved, but probably it is a `yaml-cpp` version issue.
So, i guess i will close the issue for now.

**Comment by EricVoll** [comment]
@brunoeducsantos have you ever figured out which yaml-cpp version to use? I am facing the same issue. I've tried 0.6.0, 0.3.0 and 0.2.7 without success so far.
