### ISSUE TITLE
Is there a new release for melodic planned?

### ISSUE THREAD

**Issue by AlexReimann** [ANYbotics/grid_map#260]
Hello,

do you plan to make another release for melodic or are you now fully focused on ROS2?

(I was hoping to get a release with the fix https://github.com/ANYbotics/grid_map/pull/224)

**Comment by maximilianwulf** [comment]
Hey @AlexReimann, 

Sure, at the moment we continue supporting ROS1.

I think #224 was merged, have a look of the file: https://github.com/ANYbotics/grid_map/blob/master/grid_map_core/include/grid_map_core/iterators/LineIterator.hpp#L112
