### ISSUE TITLE
grid map visualization & convert to image

### ISSUE THREAD

**Issue by kwangwookyun** [ANYbotics/grid_map#261]
I want the following 2 things.

1. I want to convert the result of the visualization in rviz with color to an image (figure 1 in Rviz to image data in ROS)
2. I want to merge it with the camera image. So, I need to convert from visualization result in rviz to CV type.

![캡처](https://user-images.githubusercontent.com/27790689/93459015-0e261a00-f91c-11ea-9c00-64a5be42927b.PNG)
figure 1.  the result of the visualization in rviz with color

Currently I use the grid_map_cv package to convert the gridmap to cv, but it is different from the result of being created as a black and white image and visualrized in rviz.

Is there any way I can do the 2 things I want? Please Any help would be appreciated.

**Comment by maximilianwulf** [comment]
Hey @kwangwookyun ,

> I want to convert the result of the visualization in rviz with color to an image (figure 1 in Rviz to image data in ROS)

Yes, use the opencv function `applyColorMap`. You can use the technique described in this thread: https://stackoverflow.com/questions/13840013/opencv-how-to-visualize-a-depth-image

> I want to merge it with the camera image. So, I need to convert from visualization result in rviz to CV type.

Can you elaborate on this idea?

**Comment by kwangwookyun** [comment]
> Hey @kwangwookyun ,
> 
> > I want to convert the result of the visualization in rviz with color to an image (figure 1 in Rviz to image data in ROS)
> 
> Yes, use the opencv function `applyColorMap`. You can use the technique described in this thread: https://stackoverflow.com/questions/13840013/opencv-how-to-visualize-a-depth-image
> 
> > I want to merge it with the camera image. So, I need to convert from visualization result in rviz to CV type.
> 
> Can you elaborate on this idea?

@maximilianwulf
Thanks for answering.

- merging grid map image with camera image means overlay .

The grid map data type is visualized through rviz as shown in figure 1.

I want to convert the result visualized in rviz into an image and "overlap" it with the camera image.
This will be shown in a form similar to AR(augmented reality).

As a result, i want to visualize it as follows. (Figure 3)

Figure 2. Before to merge
![image](https://user-images.githubusercontent.com/27790689/94813358-d4ccce80-0432-11eb-99a7-9c7330031987.png)





Figure 3. result overlay gridmap to camera image
![image](https://user-images.githubusercontent.com/27790689/94813377-da2a1900-0432-11eb-96d1-6cddf03b4644.png)




In order to look like the above, the rviz visualization result must be converted into an image. I want to do this.
The opencv_demo package converts the gridmap to an image, but it is not visualized like rviz

**Comment by maximilianwulf** [comment]
Hey @kwangwookyun, I think RVIZ can generate this for you, right? 

So if you choose 
![Screenshot from 2020-10-06 16-36-13](https://user-images.githubusercontent.com/5656831/95216275-2b028e80-07f2-11eb-97cc-ecdf65e89d82.png)

you get this description

![Screenshot from 2020-10-06 16-36-18](https://user-images.githubusercontent.com/5656831/95216278-2c33bb80-07f2-11eb-824c-14c9f6b9dca7.png)

and the image will render everything as an image what is currently visible. 

![Screenshot from 2020-10-06 16-33-35](https://user-images.githubusercontent.com/5656831/95216123-fe4e7700-07f1-11eb-97fe-0b5daf64cae9.png)

> The opencv_demo package converts the gridmap to an image, but it is not visualized like rviz

The output of the grid_map_cv is an image that is seen from above the grid map. If you want to overlay it on a 3D scene you would have to do the projections by yourself.

**Comment by kwangwookyun** [comment]
thank you! I solved the issue.
