### ISSUE TITLE
Convert SubGeometryMap to image

### ISSUE THREAD

**Issue by brunoeducsantos** [ANYbotics/grid_map#264]
Hi, 
Is there a way to convert `SubGeometryMap` to an `OpenCV matrix` ? I am aware that we can do it for a `GridMap` , but not sure for `SubGeom`. 
Regards,
Bruno

**Comment by maximilianwulf** [comment]
Did you find the solution?

**Comment by brunoeducsantos** [comment]
I didn't find a solution. Just a hack by converting a sub-grid to a grid map.
