### ISSUE TITLE
Compile error help ...

### ISSUE THREAD

**Issue by thezest76** [ANYbotics/grid_map#265]
Hello,

While I was trying to compile the package, I met the error below. 
Could you tell me how to fix this problem ?

My system is Ubuntu 2020 + ROS noetic

Best,

> 
> In file included from /opt/ros/noetic/include/rviz/message_filter_display.h:37,
>                  from /home/hankm/catkin_ws/src/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/message_filter_display.h:13,
>                  from /home/hankm/catkin_ws/build/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/../../../../../src/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/GridMapDisplay.hpp:15,
>                  from /home/hankm/catkin_ws/build/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/moc_GridMapDisplay.cpp:9:
> /opt/ros/noetic/include/rviz/display_context.h: In member function ‘std::shared_ptr<tf2_ros::Buffer> rviz::DisplayContext::getTF2BufferPtr() const’:
> /opt/ros/noetic/include/rviz/display_context.h:100:31: error: ‘class rviz::FrameManager’ has no member named ‘getTF2BufferPtr’
>   100 |     return getFrameManager()->getTF2BufferPtr();
>

**Comment by maximilianwulf** [comment]
Hey @thezest76, the library is currently not upgraded to Noetic, this will happen soon. In the meantime, you can check out the branch from this MR to compile it. https://github.com/ANYbotics/grid_map/pull/231

**Comment by thezest76** [comment]
Hello,

Thanks for the quick response.
Could you please tell what would be the branch name ?
Are we talking about bf0be3a ?  How do I check-out this commit from my
local directory ?

Best,

**Comment by maximilianwulf** [comment]
It is from a forked repo: https://github.com/jspricke/grid_map/tree/noetic

You can read more about git on this blog post: https://www.tomasbeuzen.com/post/git-fork-branch-pull/

**Comment by thezest76** [comment]
Thanks for the kind explanation.
It is working now.

Best,

**Comment by maximilianwulf** [comment]
Glad to hear. Thank you for using grid map.

**Comment by liuzm-slam** [comment]
how do you deal with this problem? i have the same problem, i need your help

**Comment by maximilianwulf** [comment]
Hi @liuzm-slam can you give a bit more context, which version of OS are you using and which ROS version? 

Can you also add your specific error?
