### ISSUE TITLE
release package as binary ROS2

### ISSUE THREAD

**Issue by nik-tier4** [ANYbotics/grid_map#268]
When can we expect the binary package release for ROS2?

**Comment by SteveMacenski** [comment]
We're still working on a port

**Comment by divgill91** [comment]
Any progress on this? Is it an issue of not enough resources to work on a port or is it a difficult task?

**Comment by SteveMacenski** [comment]
Releases will be cut once https://github.com/ANYbotics/grid_map/issues/283 is done. Closing redundant intent
