### ISSUE TITLE
It seems that we cannot set orientation of map ?, 

### ISSUE THREAD

**Issue by jediofgever** [ANYbotics/grid_map#281]
is a there a way to set orientation of map without messing with the data represented in the map? 

I am aware that I can just use a `tf_static_transfrom` publisher and create a dedicated frame with desired orientation but I had like to align my `grid_map` with another unified map frame, so its better to set pose of grid_map in this unified map frame.

**Comment by maximilianwulf** [comment]
Hi @jediofgever, there is currently no option to set the orientation of the grid map, only the position. 

You will have to do it as you mentioned. 

What you can do, is actively transform a grid map from one frame to another given a transformation. Check out this [function](https://github.com/ANYbotics/grid_map/blob/master/grid_map_cv/include/grid_map_cv/GridMapCvProcessing.hpp#L45).
