### ISSUE TITLE
problem while installing grid_map_cv package:     fatal error: filters/filter_base.hpp: can't find that file or directory

### ISSUE THREAD

**Issue by mark9714** [ANYbotics/grid_map#292]
<img width="1377" alt="截屏2021-04-07 上午9 33 42" src="https://user-images.githubusercontent.com/71640010/113797994-dd58e580-9784-11eb-9291-ed5803fff2b7.png">

When I try to install grid_map,I've got some problem like this.Did any body have something like this?Actually,I don't know what the filters library is.

**Comment by bach05** [comment]
Hi, 
I had the some problem. I solved by substitute in every file `<filters/*.hpp>` with `<filters/*.h>`.

It works fine up to now.

**Comment by mark9714** [comment]
@bach05 thank you so much!!I have solved the problem with your help.

**Comment by fantasyplus** [comment]
still not help..

**Comment by maximilianwulf** [comment]
Just to be sure, you experienced these issues with melodic, right?

**Comment by rosrookie** [comment]
> Hi, I had the some problem. I solved by substitute in every file `<filters/*.hpp>` with `<filters/*.h>`.
> 
> It works fine up to now.

Works for me too, thanks. This happens on ros melodic.

**Comment by WfHit** [comment]
So, using " _ln -s /opt/ros/melodic/include/filters/filter_base.h /opt/ros/melodic/include/filters/filter_base.hpp_ " seems more convenient ^^
