### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by Psyduck123** [ANYbotics/grid_map#295]
Thanks for your great work! I faced an error when I do the  $catkin build grid_map in my ROS work space :

home/elevation_ws/src/grid_map/grid_map_cv/InpainFilter.hpp:11:10: fatal error: filters/filter_base.hpp : No such file or directory
#include <filters/filter_base.hpp>
                 ^~~~~~~~~~~~~~
compilation terminated

Is there any way could solve this issue? Thanks a lot!

**Comment by bach05** [comment]
Hi, see here #292 .

**Comment by Psyduck123** [comment]
@bach05  Thanks a lot! that's works. Lots of files need to be modified. XD
