### ISSUE TITLE
How to store point cloud data by 3dLiDAR in the grid

### ISSUE THREAD

**Issue by S-konoa** [ANYbotics/grid_map#315]
I want to partition the point cloud data of 3dLiDAR with a grid and process the point cloud in each grid. Therefore, I want to store the point cloud data of the point cloud processing library PCL in the grid created by gridmap_simple_demo (simple_demo.cpp), but I don't know how. Could you please tell me how to add point cloud data to the grid?

**Comment by maximilianwulf** [comment]
Hey, does elevation mapping do what you want? https://github.com/ANYbotics/elevation_mapping

**Comment by S-konoa** [comment]
thank you for reply.
I'll try.

**Comment by maximilianwulf** [comment]
I assume it has worked. Feel free to re-open if you need further assistance.
