### ISSUE TITLE
Ray tracing to update grid map?

### ISSUE THREAD

**Issue by sgarciav** [ANYbotics/grid_map#322]
I'm currently using the grid map package to keep an updated occupancy grid of free vs non-free space. With each new incoming point cloud I update my grid map by updating the grid cells that correspond to the coordinates in the point cloud (i.e., grid cells not observed by the sensors are not updated).

I'd like to improve the update process and implement ray tracing. The goal is to update the grid cells in between the sensor and a given detection. So, instead of just updating the grid cells that correspond to a detection, all the grid cells in between (the camera and the detection) will also be updated (as clear space).

Instead of implementing code from scratch, wanted to first explore any existing libraries (provided by this package or otherwise) that can accomplish the same. I've searched online and found nothing so far. Does this `grid_map` package implement such functionality?

Any comments/suggestions are more than welcomed.
Thanks in advance!

**Comment by MaverickPeter** [comment]
You may want to refer https://github.com/ZJU-Robotics-Lab/GEM  this repo implements ray tracing in cuda.

**Comment by pfankhauser** [comment]
There's a [line iterator](https://github.com/ANYbotics/grid_map/blob/master/grid_map_core/include/grid_map_core/iterators/LineIterator.hpp) in Grid Map we have been using to implement simple ray tracing. Maybe this method can provide you with what you need?

**Comment by sgarciav** [comment]
@pfankhauser sweet thanks! I'll take a look.

**Comment by sgarciav** [comment]
This line iterator helped a bunch thanks! I'm able to easily iterate in between two points and perform an action of each grid cell.
