### ISSUE TITLE
Changelogs have newer version than packages

### ISSUE THREAD

**Issue by StefanFabian** [ANYbotics/grid_map#358]
Hi,
we're using Debian packages for grid_map but since we want to stay with the state of the master, we build them ourselves.
Your recent merge has added changelogs for a version 1.7.0 but the packages are at 1.6.10.
Unfortunately, bloom doesn't like that at all and the builds fail.

Is there a reason why you've added empty changelog entries for a version that doesn't exist?

**Comment by maximilianwulf** [comment]
Should be fixed. Can you check again?

**Comment by StefanFabian** [comment]
Yes, builds again. Thanks for the quick fix! :)
