### ISSUE TITLE
Robot-Centric Elevation Mapping + Grid Map SDF

### ISSUE THREAD

**Issue by patripfr** [ANYbotics/grid_map#361]
Hi,
I'm using the elevation_mapping package to create a grid map from point clouds and I want to use the grid_map_sdf functionality to create an SDF out of it. I'm following the [demo](https://github.com/ANYbotics/grid_map/blob/master/grid_map_demos/src/SdfDemo.cpp#L40-L55) for the conversion and visualization.

While to robot is in the XY origin, this works fine and the elevation map and the sdf are aligned. 
The image below shows the occupied sdf voxels and the elevation mesh.
![Screenshot from 2022-06-27 12-37-36](https://user-images.githubusercontent.com/28986714/175931294-8ccea77b-a20b-463c-9e66-ada928cb4622.png)

However, once the robot moves, the location of the sdf does not update correctly and creates wrong values as indicated in the below figure. While the "overlapping" area seems fine, the values in the newly observed area on the left side of the image are attached on the right side instead of the (correct) left one.
![Screenshot from 2022-06-27 12-36-15](https://user-images.githubusercontent.com/28986714/175931790-5ce090fd-eda0-49a9-9cee-0a1b89a3471e.png)

 Am I missing something here or is the combination of grid_maps from the elevation_mapping packes with the grid_map_sdf package not supported?

**Comment by maximilianwulf** [comment]
Looks like a indice mismatch to me. 

How do you trigger re-computation of the sdf after the robot has moved?

**Comment by patripfr** [comment]
Calling `convertToDefaultStartIndex()` fixed it! Thanks a lot!
