### ISSUE TITLE
GridMapPclConverter consume really long time from polygonmesh2gridmap

### ISSUE THREAD

**Issue by Kin-Zhang** [ANYbotics/grid_map#362]
![image](https://user-images.githubusercontent.com/35365764/177074183-e7415375-b3a5-45bc-ab5d-e0c12033c06c.png)

first, it will build mesh through vdbfusion, but when I convert it to PCL polygon mesh with filtered a number of points also, but it still consumes lots of time, I'm wondering that is it normal for this script converter? through I knew the converter did ray intersection with each mesh on the grid. But it still wried if it has to use so much time...

https://github.com/ANYbotics/grid_map/blob/master/grid_map_pcl/src/GridMapPclConverter.cpp

Using ubuntu 20.04 with ROS noetic

**Comment by maximilianwulf** [comment]
I guess the bottleneck is 

```
  for (const pcl::Vertices& polygon : mesh.polygons) {
```

How big is your mesh?

**Comment by Kin-Zhang** [comment]
as the figure shows, the mesh has 1287 vertices, each vertice has three other vertices' id which is the for loop one.

I assume the same thing. but it still costs too much time, just wried... maybe also the ray intersection on all polygons

**Comment by maximilianwulf** [comment]
you can try to find the the hotspot with `Intel vtune`.
