### ISSUE TITLE
grid map alignment [feature]

### ISSUE THREAD

**Issue by narutojxl** [ANYbotics/grid_map#363]
Hello, authors,
If I have a local grid_map, i want to alignment it with the global grid map created by some 2d slam system. Do we already have implemented this function in the lib?
Thanks for your reply and help.

**Comment by maximilianwulf** [comment]
Does https://github.com/ANYbotics/grid_map/blob/master/grid_map_core/include/grid_map_core/GridMap.hpp#L324 do what you want?

**Comment by narutojxl** [comment]
thanks a lot, closed it now.
