### ISSUE TITLE
Compilation bug in foxy-devel where variable outputColor is not initialzied in pkg grid_map_filters

### ISSUE THREAD

**Issue by xaru8145** [ANYbotics/grid_map#395]
Hi,

There is a compilation bug in foxy-devel branch in file grid_map_filters/src/ColorBlendingFilter.cpp where the variable outputColor of type Eigen::Array3f is not initialized. This has been solved in branch humble in commit [0e21cfd](https://github.com/ANYbotics/grid_map/commit/0e21cfdbca94ea2adad5a1c4eda65b4d1ca4889a) but not in foxy-devel.

I have opened a pull request to merge this change to foxy-devel: https://github.com/ANYbotics/grid_map/pull/394

**Comment by Ryanf55** [comment]
Hi there,

Since Foxy is EOL, and this is merged in all maintained distros, I don't plan to backport it. If you are still on `foxy`, I recommend upgrading.
