### ISSUE TITLE
unable to build grid_map on ros2 humble

### ISSUE THREAD

**Issue by Claudio-Chies** [ANYbotics/grid_map#409]
its basically two problems at the same time:
first ```colcon build --symlink-install --packages-up-to pcl_ros ``` throws me ``` Package 'pcl_ros' specified with --packages-up-to was not found ``` (same issue as in [old Issue](https://github.com/ANYbotics/grid_map/issues/371))

i was able to fix this problem with two things:
take the fix from the issue above and change the branch of perception_pcl from foxy-devel to ros2 (proposed PR: https://github.com/ANYbotics/grid_map/pull/407)
and then clone the humble branch instead of the ros 2 branch in the readme (Updated Readme PR: https://github.com/ANYbotics/grid_map/pull/408)

**Comment by Ryanf55** [comment]
The part of this we need to fix was done, so no changes are needed. Please open if you have further needs in `humble`.
