### ISSUE TITLE
Visualize multiple grid maps in rviz

### ISSUE THREAD

**Issue by SDADEEC** [ANYbotics/grid_map#411]
Hi, I tried to save multiple grid maps into a vector and loop through the vector to publish them one by one to the same topic and visualize  them in rviz. In rviz, I also set the `History Length` to 100 so that I can check all grid maps in the vector simultaneously. 

When the vector size is small (e.g., less than 50), rviz only shows some of them but it doesn't crush. But when the vector size becomes bigger, rviz crushes and throw `std::bad_alloc`.

I'm wondering if there is any rviz plugin that can show a vector of grid maps (like `nav_msgs/Path` for `geometry_msgs/PoseStamped`) or is there any proper way to show all grid maps in a vector in rviz?

**Comment by Ryanf55** [comment]
You are running out of memory. My best recommendation is to decimate the maps to a lower resolution so they consume less memory.
